-- Migration v018: CIE-10 dental/stomatological subset (chapter K00-K14).
-- Reference catalog so doctors can search a diagnosis code by code or text.
-- Descriptions are the official Spanish CIE-10 labels for the oral/dental block.

CREATE TABLE IF NOT EXISTS cie10_codes (
    code TEXT PRIMARY KEY,
    description TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cie10_desc ON cie10_codes(description);

INSERT OR IGNORE INTO cie10_codes (code, description) VALUES
('K000', 'Anodoncia'),
('K001', 'Dientes supernumerarios'),
('K002', 'Anomalías del tamaño y de la forma del diente'),
('K003', 'Dientes moteados'),
('K004', 'Alteraciones en la formación dentaria'),
('K005', 'Alteraciones hereditarias de la estructura dentaria, no clasificadas en otra parte'),
('K006', 'Alteraciones en la erupción dentaria'),
('K007', 'Síndrome de erupción dentaria'),
('K008', 'Otros trastornos del desarrollo dentario'),
('K009', 'Trastorno del desarrollo dentario, no especificado'),
('K010', 'Dientes no erupcionados'),
('K011', 'Dientes impactados'),
('K020', 'Caries limitada al esmalte'),
('K021', 'Caries de la dentina'),
('K022', 'Caries del cemento'),
('K023', 'Caries dentaria detenida'),
('K024', 'Odontoclasia'),
('K025', 'Caries dental con exposición pulpar'),
('K028', 'Otras caries dentales'),
('K029', 'Caries dental, no especificada'),
('K030', 'Atrición excesiva de los dientes'),
('K031', 'Abrasión de los dientes'),
('K032', 'Erosión de los dientes'),
('K033', 'Reabsorción patológica de los dientes'),
('K034', 'Hipercementosis'),
('K035', 'Anquilosis dental'),
('K036', 'Depósitos [acreciones] en los dientes'),
('K037', 'Cambios posteruptivos del color de los tejidos dentales duros'),
('K038', 'Otras enfermedades especificadas de los tejidos duros de los dientes'),
('K039', 'Enfermedad de los tejidos duros de los dientes, no especificada'),
('K040', 'Pulpitis'),
('K041', 'Necrosis de la pulpa'),
('K042', 'Degeneración de la pulpa'),
('K043', 'Formación anormal de tejido duro en la pulpa'),
('K044', 'Periodontitis apical aguda originada en la pulpa'),
('K045', 'Periodontitis apical crónica'),
('K046', 'Absceso periapical con fístula'),
('K047', 'Absceso periapical sin fístula'),
('K048', 'Quiste radicular'),
('K049', 'Otras enfermedades y las no especificadas de la pulpa y del tejido periapical'),
('K050', 'Gingivitis aguda'),
('K051', 'Gingivitis crónica'),
('K052', 'Periodontitis aguda'),
('K053', 'Periodontitis crónica'),
('K054', 'Periodontosis'),
('K055', 'Otras enfermedades periodontales'),
('K056', 'Enfermedad periodontal, no especificada'),
('K060', 'Retracción gingival'),
('K061', 'Hiperplasia gingival'),
('K062', 'Lesiones de la encía y de la zona edéntula asociadas con traumatismo'),
('K068', 'Otros trastornos especificados de la encía y de la zona edéntula'),
('K069', 'Trastorno de la encía y de la zona edéntula, no especificado'),
('K070', 'Anomalías evidentes del tamaño de los maxilares'),
('K071', 'Anomalías de la relación maxilobasilar'),
('K072', 'Anomalías de la relación entre los arcos dentarios'),
('K073', 'Anomalías de la posición del diente'),
('K074', 'Maloclusión, no especificada'),
('K075', 'Anomalías dentofaciales funcionales'),
('K076', 'Trastornos de la articulación temporomaxilar'),
('K078', 'Otras anomalías dentofaciales'),
('K079', 'Anomalía dentofacial, no especificada'),
('K080', 'Exfoliación de dientes debida a causas sistémicas'),
('K081', 'Pérdida de dientes debida a accidente, extracción o enfermedad periodontal local'),
('K082', 'Atrofia del reborde alveolar desdentado'),
('K083', 'Raíz dental retenida'),
('K088', 'Otras afecciones especificadas de los dientes y sus estructuras de sostén'),
('K089', 'Trastorno de los dientes y de sus estructuras de sostén, no especificado'),
('K090', 'Quistes originados por el desarrollo de los dientes'),
('K091', 'Quistes del desarrollo (no odontogénicos) de la región bucal'),
('K092', 'Otros quistes de los maxilares'),
('K098', 'Otros quistes especificados de la región bucal, no clasificados en otra parte'),
('K099', 'Quiste de la región bucal, no especificado'),
('K100', 'Trastornos del desarrollo de los maxilares'),
('K101', 'Granuloma central de células gigantes'),
('K102', 'Afecciones inflamatorias de los maxilares'),
('K103', 'Alveolitis del maxilar'),
('K108', 'Otras enfermedades especificadas de los maxilares'),
('K109', 'Enfermedad de los maxilares, no especificada'),
('K110', 'Atrofia de glándula salival'),
('K111', 'Hipertrofia de glándula salival'),
('K112', 'Sialoadenitis'),
('K113', 'Absceso de glándula salival'),
('K114', 'Fístula de glándula salival'),
('K115', 'Sialolitiasis'),
('K116', 'Mucocele de glándula salival'),
('K117', 'Trastornos de la secreción salival'),
('K118', 'Otras enfermedades de las glándulas salivales'),
('K119', 'Enfermedad de la glándula salival, no especificada'),
('K120', 'Estomatitis aftosa recurrente'),
('K121', 'Otras formas de estomatitis'),
('K122', 'Celulitis y absceso de boca'),
('K130', 'Enfermedades de los labios'),
('K131', 'Mordedura del labio y de la mejilla'),
('K132', 'Leucoplasia y otras alteraciones del epitelio bucal, incluida la lengua'),
('K133', 'Leucoplasia pilosa'),
('K134', 'Granuloma y lesiones semejantes de la mucosa bucal'),
('K135', 'Fibrosis de la submucosa bucal'),
('K136', 'Hiperplasia irritativa de la mucosa bucal'),
('K137', 'Otras lesiones y las no especificadas de la mucosa bucal'),
('K140', 'Glositis'),
('K141', 'Lengua geográfica'),
('K142', 'Glositis romboidea mediana'),
('K143', 'Hipertrofia de las papilas linguales'),
('K144', 'Atrofia de las papilas linguales'),
('K145', 'Lengua plegada'),
('K146', 'Glosodinia'),
('K148', 'Otras enfermedades de la lengua'),
('K149', 'Enfermedad de la lengua, no especificada');
